main: fr.kazotaruumc72.etherealportals.EtherealPortals
name: EtherealPortals
version: "1.1.5"
api-version: "1.21.1"
author: shweit,kazotaruumc72
description: A mystical portal plugin for fast travel between locations
website: https://github.com/shweit/EtherealPortals
folia-supported: true

commands:
  portal:
    description: Main command for EtherealPortals
    usage: "§cUsage: /portal <group|icon> <subcommand>"
    aliases: [portals, ep, etherealportals]
    permission: portal.use
  epdebug:
    description: Debug commands for EtherealPortals
    usage: "§cUsage: /epdebug <check|hitbox|location>"
    permission: portal.admin

permissions:
  # Admin permissions
  portal.admin:
    description: Grants all portal admin permissions
    default: op
    children:
      portal.group.create: true
      portal.group.delete: true
      portal.group.add: true
      portal.group.remove: true
      portal.icon.add: true
      portal.icon.remove: true
      portal.icon.list: true
      portal.item.give: true

  # Base permission
  portal.use:
    description: Allows use of /portal command
    default: true

  # Group management permissions
  portal.group.create:
    description: Allows creating portal groups
    default: op

  portal.group.delete:
    description: Allows deleting portal groups
    default: op

  portal.group.add:
    description: Allows adding portals to groups
    default: op

  portal.group.remove:
    description: Allows removing portals from groups
    default: op

  portal.group.list:
    description: Allows viewing all portal groups
    default: op

  # Icon management permissions
  portal.icon.add:
    description: Allows adding custom icons
    default: op

  portal.icon.remove:
    description: Allows removing custom icons
    default: op

  portal.icon.list:
    description: Allows viewing all icons
    default: op

  # Portal item permissions
  portal.item.give:
    description: Allows giving portal items to players
    default: op

  portal.item.place:
    description: Allows placing portal items
    default: true

  portal.item.break:
    description: Allows breaking portal items
    default: true

  portal.group.use.*:
    description: Allows using all portal groups
    default: true